""" FORWARD WAVELET TRANSFORM UNIT TEST """

"""
    Confirms the proper consruction of the FWT matrix for various cases of
    p and J. 
"""

"""
    For each p=4, 6, 8, 10, we will generate the FWT matrix 'F' for the function 
    f(x) = sin(x) using J=3, 4, 5, and 9 or 10. This represents the maximum 
    resolution my computer can generate without exploding. For each test, we check 
    five to six random entries in the matrix and make sure that they are what they 
    are supposed to be. We also check to make sure that the number of blank entries 
    (i.e., entires of zero) in the matrix match their theoretical value. Each test
    should run in less than five seconds or so - I did not want these to take 
    forever.

    The accepted values and the number of blank entries are based on the matrices
    generated by the Mathematica MRWT toolbox. These are known to be correct.

    %%% VERSION 2.2.1 %%%
    Prior to construction of these unit tests, I made sure that the matrices 
    produced by this Python program exactly matched what was generated by MRWT
    Mathematica. I tested each basis order up to J=11 and confirmed that
    they exactly equaled the Mathematica MRWT results. Anything higher than
    this, my computer could not handle in a reasonable amount of time.

    Yeah, in theory, matrices generated at higher resolution levels could be 
    totally wrong and I would never know. However, the purpose of this program
    is to get an idea of what is going on under-the-hood when wavelet 
    transformations are performed. It was never designed to optimize performance
    nor reach absurd levels of precision. 

"""

import unittest
import numpy as np
from FWT import FWT

""" %%% p=4 TESTS %%% """
class basisOrderFourTestFWT(unittest.TestCase):
    def test_matrix(self):
        # define function to be used
        def func(X): 
            return np.sin(X)
        
        """ CASE 1: J=3 """
        F1, d = FWT(4,3,func,0,2*np.pi,False)
        caseOneTest = [F1[0,0], F1[20,7], F1[27,22], F1[15,20], F1[21,6], F1[-1,28]]
        caseOneActual = [1, -1, 9/16, -1/16, -1/16, -5/16]
        np.testing.assert_allclose(caseOneTest, caseOneActual, atol=1e-7)
        # number of zero-entries in this matrix according to Mathematica: 960
        caseOneZeroCount = int(F1.size - np.count_nonzero(F1))
        np.testing.assert_equal(caseOneZeroCount, 960)

        """ CASE 2: J=4 """
        F2, d = FWT(4,4,func,0,2*np.pi,False)
        caseTwoTest = [F2[0,0],  F2[43,22], F2[-1,58], F2[55,42], F2[16,-1]     ]
        caseTwoActual =   [  1,        9/16,    1/16  ,  -1/16  ,    5/16      ]
        np.testing.assert_allclose(caseTwoTest, caseTwoActual, atol=1e-7)
        # number of zero-entries in this matrix according to Mathematica: 3936
        caseTwoZeroCount = int(F2.size - np.count_nonzero(F2))
        np.testing.assert_equal(caseTwoZeroCount, 3936)

        """ CASE 3: J=5 """
        F3, d = FWT(4,5,func,0,2*np.pi,False)
        caseThreeTest = [F3[0,0], F3[9,32], F3[43,44], F3[-1,124], F3[61,112]]
        caseThreeActual =   [  1   ,  -5/16 ,   9/16  ,  -5/16   ,  9/16    ]
        np.testing.assert_allclose(caseThreeTest, caseThreeActual, atol=1e-7)
        # number of zero-entries in this matrix according to Mathematica: 16032
        caseThreeZeroCount = int(F3.size - np.count_nonzero(F3))
        np.testing.assert_equal(caseThreeZeroCount, 16032)

        """ CASE 4: J=10 """
        F4, d = FWT(4,10,func,0,2*np.pi,False)
        caseFourTest = [F4[0,0], F4[-1, 4090], F4[4092,4087], F4[11,1024], F4[14,3584] ]
        caseFourActual =   [   1  ,    1/16    ,    -1       ,   9/16    ,   -1/16    ]
        np.testing.assert_allclose(caseFourTest, caseFourActual, atol=1e-7)
        # number of zero-entries in this matrix according to Mathematica: 16764960
        caseFourZeroCount = int(F4.size - np.count_nonzero(F4))
        np.testing.assert_equal(caseFourZeroCount, 16764960)


""" %%% p=6 TESTS %%% """
class basisOrderSixTestFWT(unittest.TestCase):
    def test_matrix(self):

        def func(X):
            return np.sin(X)
        
        """ CASE 1: J=3 """
        F1, d = FWT(6,3,func,0,2*np.pi,False)
        caseOneTest = [F1[0,0], F1[13,2], F1[25,4], F1[36,28], F1[-1,40]]
        caseOneActual = [    1    ,  -1     , -105/128 , 3/256    , -45/256]
        np.testing.assert_allclose(caseOneTest, caseOneActual, atol=1e-7)
        caseOneZeroCount = int(F1.size - np.count_nonzero(F1))
        np.testing.assert_equal(caseOneZeroCount, 2136)

        """ CASE 2: J=4 """
        F2, d = FWT(6,4,func,0,2*np.pi,False)
        caseTwoTest = [F2[0,0], F2[16,16], F2[26,20], F2[42,72], F2[-1,86]]
        caseTwoActual =   [   1   ,  -25/256 ,  -3/256  ,  75/128  ,   7/256  ]
        np.testing.assert_allclose(caseTwoTest, caseTwoActual, atol=1e-7)
        caseTwoZeroCount = int(F2.size - np.count_nonzero(F2))
        np.testing.assert_equal(caseTwoZeroCount, 8808)

        """ CASE 3: J=5 """
        F3, d = FWT(6,5,func,0,2*np.pi,False)
        caseThreeTest = [F3[0,0], F3[13,80], F3[31,40], F3[41, 132], F3[-1,184] ]
        caseThreeActual =   [   1   ,   7/256  ,  -25/256 ,    -1      ,  -45/256   ]
        np.testing.assert_allclose(caseThreeTest, caseThreeActual, atol=1e-7) 
        caseThreeZeroCount = int(F3.size - np.count_nonzero(F3))
        np.testing.assert_equal(caseThreeZeroCount, 35976)

        """ CASE 4: J=10 """
        F4, d = FWT(6,10,func,0,2*np.pi,False)
        caseFourTest = [F4[0,0], F4[13,512], F4[-1,6138], F4[13,256], F4[6140,6138]]
        caseFourActual =   [  1    ,  315/256  ,   63/128   ,     -1    ,   -25/256    ] 
        np.testing.assert_allclose(caseFourTest, caseFourActual, atol=1e-7)     
        caseFourZeroCount = int(F4.size - np.count_nonzero(F4))
        np.testing.assert_equal(caseFourZeroCount, 37718088)
""" %%% p=8 TESTS %%% """
class basisOrderEightTestFWT(unittest.TestCase):
    def test_matrix(self):

        def func(X):
            return np.sin(X)
        
        """ CASE 1: J=3 """
        F1, d = FWT(8,3,func,0,2*np.pi,False)
        caseOneExpected = [F1[0,0], F1[36,8] , F1[43,28], F1[48,31], F1[-1,56] ]
        caseOneActual =   [   1   , 1225/2048, -5/2048  ,    -1    , -2145/2048]
        np.testing.assert_allclose(caseOneActual, caseOneExpected, atol=1e-7)
        caseOneZeroCount = int(F1.size - np.count_nonzero(F1))
        np.testing.assert_equal(caseOneZeroCount,3776)

        """ CASE 2: J=4 """
        F2, d = FWT(8,4,func,0,2*np.pi,False)
        caseTwoExpected = [F2[0,0], F2[27,56], F2[39,32], F2[56,84], F2[-1,116] ]
        caseTwoActual =   [   1   ,  -5/2048  , -245/2048,  49/2048 , -273/2048  ]
        np.testing.assert_allclose(caseTwoActual, caseTwoExpected, atol=1e-7)
        caseTwoZeroCount = int(F2.size - np.count_nonzero(F2))
        np.testing.assert_equal(caseTwoZeroCount, 15616)

        """ CASE 3: J=5 """
        F3, d = FWT(8,5,func,0,2*np.pi,False)
        caseThreeExpected = [F3[0,0], F3[18,16], F3[255,-1], F3[-1,248], F3[19,32]]
        caseThreeActual =   [   1   , 693/2048 , -33/2048  , -2145/2048, 945/2048 ]
        np.testing.assert_allclose(caseThreeActual, caseThreeExpected, atol=1e-7)  
        caseThreeZeroCount = int(F3.size - np.count_nonzero(F3))
        np.testing.assert_equal(caseThreeZeroCount,63872)

        """ CASE 4: J=9 """
        F4, d = FWT(8,9,func,0,2*np.pi,False)
        caseFourExpected = [F4[0,0], F4[17,0], F4[4095,4094], F4[4094,4088], F4[-1,4092] ]
        caseFourActual =   [   1   , 429/2048,    693/2048  ,   -525/2048  ,  -3003/2048 ] 
        np.testing.assert_allclose(caseFourActual, caseFourExpected, atol=1e-7)     
        caseFourZeroCount = int(F4.size - np.count_nonzero(F4))
        np.testing.assert_equal(caseFourZeroCount, 16748672)

""" %%% p=10 TESTS %%% """
class basisOrderTenTestFWT(unittest.TestCase):
    def test_matrix(self):

        def func(X):
            return np.sin(X)
        
        """ CASE 1: J=3 """
        F1, d = FWT(10,3,func,0,2*np.pi,False)
        caseOneExpected = [F1[0,0],  F1[22,0] ,  F1[27,28]   , F1[38,76]  ,   F1[-1,68] ]
        caseOneActual =   [   1   , -715/65536, 19845/32768  , -2145/65536, -23205/16384]
        np.testing.assert_allclose(caseOneActual, caseOneExpected, atol=1e-7)
        caseOneZeroCount = int(F1.size - np.count_nonzero(F1))
        np.testing.assert_equal(caseOneZeroCount,5880)

        """ CASE 2: J=4 """
        F2, d = FWT(10,4,func,0,2*np.pi,False)
        caseTwoExpected = [F2[0,0],     F2[21,32] , F2[158,158], F2[158,155],   F2[-1,148] ]
        caseTwoActual =   [   1   ,  -109395/32768, -2145/65536,     -1     , -23205/16384 ]
        np.testing.assert_allclose(caseTwoActual, caseTwoExpected, atol=1e-7)
        caseTwoZeroCount = int(F2.size - np.count_nonzero(F2))
        np.testing.assert_equal(caseTwoZeroCount,24360)

        """ CASE 3: J=5 """
        F3, d = FWT(10,5,func,0,2*np.pi,False)
        caseThreeExpected = [F3[0,0],   F3[21,16]  , F3[318,315], F3[-1,314] , F3[319,-1] ]
        caseThreeActual =   [   1   , 109395/65536 ,      -1    , 51051/16384, -715/65536 ]
        np.testing.assert_allclose(caseThreeActual, caseThreeExpected, atol=1e-7)  
        caseThreeZeroCount = int(F3.size - np.count_nonzero(F3))
        np.testing.assert_equal(caseThreeZeroCount,99720)

        """ CASE 4: J=9 """
        F4, d = FWT(10,9,func,0,2*np.pi,False)
        caseFourExpected = [F4[0,0], F4[21,128], F4[21,1536] , F4[-1,5110], F4[5119,5106] ]
        caseFourActual =   [   1   ,     -1    , -23205/16384, 85085/32768,  -1755/16384  ] 
        np.testing.assert_allclose(caseFourActual, caseFourExpected, atol=1e-7)     
        caseFourZeroCount = int(F4.size - np.count_nonzero(F4))
        np.testing.assert_equal(caseFourZeroCount,26168520)