import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

""" -------------------- DENSE DATA ERROR COMPUTATION -------------------- """
"""
    This program compares the values computed via the sparse spacetime modified
    1D Burgers' problem using MRWT against the analytical solution. The dimensions
    of the solution are in both space and time, so if we extract this information
    from the dense.pvd file generated, we can compare the accuracy of our 
    approximation to the analytical solution.

    The input file 'denseParaviewInformation.csv' should be generated by loading 
    the 'dense.pvd' file generated from the 'sparseApp' application into ParaView
    and downloading the spreadsheet view of the information. This should contain
    information such as the Point ID, j-level, u-value, du/dx-value, etc. Only
    once this is generated can this code be run.  

    We will pull the spatial and temporal coordinates from this .csv, as well as
    the values computed for u, du/dx, du/dt, and d^2u/dx^2. We can compare this to
    the analytical values and see our accuracy. For now, this code only computes
    the maximum absolute error, in line with what is presented in standard 
    MRWT theory, but in theory this could be adjusted. 

    NOTE: I think that this computation is only valid for the highest level that
    is computed in the dense reconstruction. It seems that if you run 'J=n' in 
    the sparseApp, the dense reconstruction will go up to 'J=n-1'. This could be
    a case-by-case basis, but we want to make sure that we only pull values that
    are computed at the highest resolution level in the dense reconstruction. You
    CANNOT use the sparse model to compute error (for some reason)!
"""
# user-prescribed threshold used in the run
threshold = 1e-7

# name of file to import 
importFile = 'denseParaviewInformationTest26.csv'

# import the document as a pandas dataframe 
print('Importing spreadsheet...')
denseDF = pd.read_csv(importFile)
print('Succesfully imported spreadsheet.')

# grab some basic information about the data structure
rows, columns = denseDF.shape

""" -------------------------- COLUMN EXTRACTION -------------------------- """
"""
    If no preprocessing is performed on the downloaded .csv file, the following
    column names are used (listed in order, column 1 - 21):

    Point ID: ParaView-assigned ID for a given coordiante
    j: resolution level
    k_0: index in the 0th direction
    k_1: index in the 1st direction
    k_Magnitude: Euclidean norm of the index (useless, I think)
    lambda: lambda value (still not sure what this is)
    Points_0: x-coordinate
    Points_1: time coordiante
    Points_2: I have no idea
    Points_Magnitude: Euclidean norm of the point (useless?)
    trials: boolean to indicate if a point is a trial point or not
    u: u-value
    u_active: not sure what this is
    u_d: wavelet coefficient 'd' of the u-value
    u_essential: boolean to indicate if a point is essential or not
    ‚àÇu_‚àÇx: du/dx value
    ‚àÇu_‚àÇx_d: wavelet coefficient 'd' of the du/dx value
    ‚àÇu_‚àÇxx: d^2 u / d x^2 value 
    ‚àÇu_‚àÇxx_d: wavelet coefficient 'd' of the d^2 u / d x^2 value
    ‚àÇu_‚àÇy: du/dt value (the 'y' direction is the time direction)
    ‚àÇu_‚àÇy_d: wavelet coefficient 'd' of the du/dt value

    NOTE: We are going to rename the columns using more friendly characters
    for easier manipulation. You should check the .csv file to make sure that
    the above order and labeling is correct before proceeding!
"""

denseDF.columns = ['point_id', 'j', 'k0', 'k1', 'k_mag', 'lam', 'x', 't', 'z',
                   'points_mag', 'is_trial', 'u', 'u_active', 'u_wavelet_d',
                   'is_essential', 'dudx', 'dudx_d', 'dudxx', 'dudxx_d', 
                   'dudt', 'dudt_d']

# grab the column mames
columnNames = denseDF.columns

# we are only going to grab the information from the rows that have a maximum 
# resolution level
max_j = denseDF["j"].max()
filtered = denseDF[denseDF["j"] == max_j]

# extract the essential columns and construct a new dataframe (I think)? 
essentialInfo = filtered.loc[:, ["point_id", "j", "x", "t", "u", "dudx", "dudxx", "dudt"]]

# now convert this new dataframe into a numpy array to make it easier to parse
dataMatrix = essentialInfo.values

print('Essential information successfully extracted.')

""" ------------------------ ANALYTICAL SOLUTIONS ------------------------ """
"""
    This will be problem dependent, but for the modified Burgers' equation we
    use a 'tanh' profile as our initial condition and it will simply translate
    across space through time. 
"""

# problem parameters - check the output log to make sure these are right
nu = 0.05
c = 1
x0 = -0.5

# function definitions that can be called later
def exSol(x,t):
    return -np.tanh((x-x0-c*t)/(2*nu))
def exDX(x,t):
    arg = (x - x0 - c*t)/ (2*nu)
    return -(1/(2*nu)) * (1/np.cosh(arg))**2
def exDXX(x,t):
    arg = (x - x0 - c*t)/(2*nu)
    return (1/(2*nu**2)) * (1/np.cosh(arg))**2 * np.tanh(arg)
def exDT(x,t): 
    arg = (x - x0 - c*t)/(2*nu)
    return (c/(2*nu)) * (1/np.cosh(arg))**2

""" ------------------------- ERROR COMPUTATIONS ------------------------- """
"""
    Can directly generate the analytical vectors by passing the columns of the
    'dataMatrix' into the function arguments above. We can store error arrays 
    and the maxium errors for each as well. 
"""

analyticalU = exSol(dataMatrix[:,2], dataMatrix[:,3])
errorU = np.abs(analyticalU - dataMatrix[:,4])
maxErrorU = np.max(errorU)
print(f'Maximum u Absolute Error: ', maxErrorU)

analyticalDUDX = exDX(dataMatrix[:,2], dataMatrix[:,3])
errorDUDX = np.abs(analyticalDUDX - dataMatrix[:,5])
maxErrorDUDX = np.max(errorDUDX)
print(f'Maximum du/dx Absolute Error: ', maxErrorDUDX)

analyticalDUDXX = exDXX(dataMatrix[:,2], dataMatrix[:,3])
errorDUDXX = np.abs(analyticalDUDXX - dataMatrix[:,6])
maxErrorDUDXX = np.max(errorDUDXX)
print(f'Maximum du/dxx Absolute Error: ', maxErrorDUDXX)

analyticalDUDT = exDT(dataMatrix[:,2], dataMatrix[:,3])
errorDUDT = np.abs(analyticalDUDT - dataMatrix[:,7])
maxErrorDUDT = np.max(errorDUDT)
print(f'Maximum du/dt Absolute Error: ', maxErrorDUDT)

if (np.max(errorU) < 10*threshold):
    print(f'Function approximation value is on order of magnitude of user-specified threshold, epsilon=', threshold)
else:
    print('##### ERROR ####')
    print('approximation does not meet user specified order-of-accuracy.')
    print(f'Maximum absolute error achieved: {maxErrorU}, does not meet order of accuracy {threshold}.')
